package auth

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"time"

	"github.com/hidxt/qoqtun/internal/platform/atomicfile"
)

// TokenRecord is one persisted token entry (tokens.json, 0600).
// Only Hash is stored — never the plaintext.
type TokenRecord struct {
	TokenID   string    `json:"token_id"`
	Hash      string    `json:"hash"` // SHA-256 hex of the plaintext
	ExpiresAt time.Time `json:"expires_at"`
	Used      bool      `json:"used"`
	Revoked   bool      `json:"revoked"`
	CreatedBy string    `json:"created_by,omitempty"`
	CreatedAt time.Time `json:"created_at"`
}

// TokenStore is a thread-safe JSON-persisted token registry. To support the
// standalone `enroll serve` process seeing tokens created by the separate
// `client create-token` process, the backing file is re-read whenever its
// mtime/size changes (see reloadIfChanged).
type TokenStore struct {
	mu       sync.RWMutex
	path     string
	now      func() time.Time // injectable clock for tests
	byID     map[string]TokenRecord
	lastMod  time.Time
	lastSize int64
}

// LoadTokenStore loads tokens from path; a missing file yields an empty
// store. now injects the clock (nil => time.Now).
func LoadTokenStore(path string, now func() time.Time) (*TokenStore, error) {
	if now == nil {
		now = time.Now
	}
	s := &TokenStore{path: path, now: now, byID: make(map[string]TokenRecord)}
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return s, nil
		}
		return nil, fmt.Errorf("auth: read token store %q: %w", path, err)
	}
	if err := s.replaceFrom(data); err != nil {
		return nil, fmt.Errorf("auth: parse token store %q: %w", path, err)
	}
	if fi, statErr := os.Stat(path); statErr == nil {
		s.lastMod = fi.ModTime()
		s.lastSize = fi.Size()
	}
	return s, nil
}

// replaceFrom rebuilds the in-memory map from raw JSON.
func (s *TokenStore) replaceFrom(data []byte) error {
	var records []TokenRecord
	if err := json.Unmarshal(data, &records); err != nil {
		return err
	}
	s.byID = make(map[string]TokenRecord, len(records))
	for _, r := range records {
		if r.TokenID == "" {
			continue
		}
		s.byID[r.TokenID] = r
	}
	return nil
}

// reloadIfChanged re-reads the backing file when it changed on disk
// (cross-process sync for the standalone enroll serve). Caller must hold
// the write lock. Failures keep the in-memory state (fail-closed).
func (s *TokenStore) reloadIfChanged() {
	fi, err := os.Stat(s.path)
	if err != nil {
		return // file missing: keep in-memory state
	}
	if fi.Size() == s.lastSize && fi.ModTime().Equal(s.lastMod) {
		return
	}
	data, err := os.ReadFile(s.path)
	if err != nil {
		return
	}
	if err := s.replaceFrom(data); err != nil {
		return
	}
	s.lastMod = fi.ModTime()
	s.lastSize = fi.Size()
}

// Create records a new token (hash only) with the given TTL and returns
// the record. The plaintext was already generated by CreateToken.
func (s *TokenStore) Create(plaintext, tokenID, createdBy string, ttl time.Duration) (TokenRecord, error) {
	if ttl <= 0 || ttl > 24*time.Hour {
		return TokenRecord{}, fmt.Errorf("auth: token TTL must be in (0, 24h] (got %s)", ttl)
	}
	if tokenID == "" || plaintext == "" {
		return TokenRecord{}, fmt.Errorf("auth: token id and plaintext required")
	}
	rec := TokenRecord{
		TokenID:   tokenID,
		Hash:      HashToken(plaintext),
		ExpiresAt: s.now().Add(ttl),
		CreatedBy: createdBy,
		CreatedAt: s.now().UTC(),
	}
	s.mu.Lock()
	s.byID[tokenID] = rec
	err := s.saveLocked()
	s.mu.Unlock()
	if err != nil {
		return TokenRecord{}, err
	}
	return rec, nil
}

// Consume validates a plaintext token and atomically marks it used.
// It returns the token id. The consumption happens under the write lock so
// concurrent requests can never double-spend a token (fail-closed: first
// caller wins, losers get ErrTokenUsed).
func (s *TokenStore) Consume(plaintext string) (string, error) {
	hash := HashToken(plaintext)
	now := s.now()

	s.mu.Lock()
	defer s.mu.Unlock()

	// Pick up tokens created by another process (standalone enroll serve).
	s.reloadIfChanged()

	// Find the matching record FIRST: purging before the lookup would
	// misreport expired tokens as invalid.
	var id string
	for tid, rec := range s.byID {
		if rec.Hash == hash {
			id = tid
			break
		}
	}
	if id == "" {
		s.purgeExpiredLocked(now)
		_ = s.saveLocked()
		return "", ErrTokenInvalid
	}
	rec := s.byID[id]
	if rec.Revoked {
		return "", ErrTokenRevoked
	}
	if now.After(rec.ExpiresAt) {
		// lazily clean up this and any other expired entries
		s.purgeExpiredLocked(now)
		_ = s.saveLocked()
		return "", ErrTokenExpired
	}
	if rec.Used {
		return "", ErrTokenUsed
	}
	rec.Used = true
	s.byID[id] = rec
	if err := s.saveLocked(); err != nil {
		return "", fmt.Errorf("auth: persist token consumption: %w", err)
	}
	return id, nil
}

// Revoke marks a token revoked by id.
func (s *TokenStore) Revoke(tokenID string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	rec, ok := s.byID[tokenID]
	if !ok {
		return fmt.Errorf("auth: token %q not found", tokenID)
	}
	rec.Revoked = true
	s.byID[tokenID] = rec
	return s.saveLocked()
}

// Get returns a copy of a record.
func (s *TokenStore) Get(tokenID string) (TokenRecord, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	rec, ok := s.byID[tokenID]
	return rec, ok
}

// All returns a snapshot sorted by token id.
func (s *TokenStore) All() []TokenRecord {
	s.mu.RLock()
	defer s.mu.RUnlock()
	out := make([]TokenRecord, 0, len(s.byID))
	for _, r := range s.byID {
		out = append(out, r)
	}
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j].TokenID < out[j-1].TokenID; j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}

// purgeExpiredLocked removes expired records (caller holds the lock).
func (s *TokenStore) purgeExpiredLocked(now time.Time) {
	for id, rec := range s.byID {
		if now.After(rec.ExpiresAt) && !rec.Used {
			delete(s.byID, id)
		}
	}
}

// saveLocked persists the store; the caller MUST hold the write lock
// (save takes no lock itself to avoid RWMutex write->read deadlock).
func (s *TokenStore) saveLocked() error {
	records := make([]TokenRecord, 0, len(s.byID))
	for _, r := range s.byID {
		records = append(records, r)
	}
	data, err := json.MarshalIndent(records, "", "  ")
	if err != nil {
		return fmt.Errorf("auth: marshal token store: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(s.path), 0o700); err != nil {
		return fmt.Errorf("auth: create token dir: %w", err)
	}
	if err := atomicfile.Write(s.path, append(data, '\n'), 0o600); err != nil {
		return fmt.Errorf("auth: save token store: %w", err)
	}
	return nil
}
